"""Add arm_turn_angle to Shovel

Revision ID: 049327069ed2
Revises: 77aa09bc992e
Create Date: 2025-08-18 16:40:34.202072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049327069ed2'
down_revision = '77aa09bc992e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shovel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arm_turn_angle', sa.Float(), server_default='90', nullable=False))

    with op.batch_alter_table('shovel_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arm_turn_angle', sa.Float(), server_default='90', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shovel_template', schema=None) as batch_op:
        batch_op.drop_column('arm_turn_angle')

    with op.batch_alter_table('shovel', schema=None) as batch_op:
        batch_op.drop_column('arm_turn_angle')

    # ### end Alembic commands ###
