"""Add Scenario model

Revision ID: 173b757501f6
Revises: a06b87cc0807
Create Date: 2025-08-13 15:42:54.840096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173b757501f6'
down_revision = 'a06b87cc0807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario',
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_auto_truck_distribution', sa.Boolean(), nullable=False),
    sa.Column('quarry_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quarry_id'], ['quarry.id'], name=op.f('fk_scenario_quarry_id_quarry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario')
    # ### end Alembic commands ###
