"""Add Blasting model

Revision ID: 2f3ca3217c27
Revises: a43abb6acab2
Create Date: 2025-09-22 11:40:17.455062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f3ca3217c27'
down_revision = '8d394792dc14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blasting',
    sa.Column('geojson_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quarry_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quarry_id'], ['quarry.id'], name=op.f('fk_blasting_quarry_id_quarry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blasting'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blasting')
    # ### end Alembic commands ###
