"""drop columns

Revision ID: 34d2db5b9f3c
Revises: 689dff3c9f22
Create Date: 2025-08-05 13:52:14.784004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d2db5b9f3c'
down_revision = '689dff3c9f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shovel', schema=None) as batch_op:
        batch_op.drop_column('wear_rate')
        batch_op.drop_column('driver_rating')
        batch_op.drop_column('init_cycles')

    with op.batch_alter_table('shovel_template', schema=None) as batch_op:
        batch_op.drop_column('wear_rate')
        batch_op.drop_column('driver_rating')
        batch_op.drop_column('init_cycles')

    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.alter_column('body_volume', new_column_name='body_capacity')
        batch_op.drop_column('driver_rating')

    with op.batch_alter_table('truck_template', schema=None) as batch_op:
        batch_op.alter_column('body_volume', new_column_name='body_capacity')
        batch_op.drop_column('driver_rating')

    with op.batch_alter_table('unload', schema=None) as batch_op:
        batch_op.drop_column('temperature')

    with op.batch_alter_table('unload_template', schema=None) as batch_op:
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unload_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    with op.batch_alter_table('unload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    with op.batch_alter_table('truck_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('body_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('body_capacity')

    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('body_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('body_capacity')

    with op.batch_alter_table('shovel_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('init_cycles', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('driver_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('wear_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    with op.batch_alter_table('shovel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('init_cycles', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('driver_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('wear_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
