"""Initial migration (attempt 3)

Revision ID: 5e034f7cece7
Revises: 
Create Date: 2025-07-23 09:33:58.525844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e034f7cece7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shovel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('initial_lat', sa.Float(), nullable=False),
    sa.Column('initial_lon', sa.Float(), nullable=False),
    sa.Column('initial_height', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_calc_enabled', sa.Boolean(), nullable=False),
    sa.Column('bucket_volume', sa.Float(), nullable=False),
    sa.Column('bucket_lift_speed', sa.Float(), nullable=False),
    sa.Column('arm_turn_speed', sa.Float(), nullable=False),
    sa.Column('bucket_dig_speed', sa.Float(), nullable=False),
    sa.Column('bucket_fill_speed', sa.Float(), nullable=False),
    sa.Column('bucket_fill_coef', sa.Float(), nullable=False),
    sa.Column('arm_inertia_coef', sa.Float(), nullable=False),
    sa.Column('return_move_coef', sa.Float(), nullable=False),
    sa.Column('payload_type', sa.Enum('GRAVEL', 'SAND', 'CLAY', 'WET_ORE', name='payloadtype'), nullable=False),
    sa.Column('init_cycles', sa.Integer(), nullable=False),
    sa.Column('wear_rate', sa.Float(), nullable=False),
    sa.Column('driver_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shovel'))
    )
    op.create_table('truck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('initial_lat', sa.Float(), nullable=False),
    sa.Column('initial_lon', sa.Float(), nullable=False),
    sa.Column('initial_height', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_calc_enabled', sa.Boolean(), nullable=False),
    sa.Column('body_volume', sa.Float(), nullable=False),
    sa.Column('speed_empty', sa.Float(), nullable=False),
    sa.Column('speed_loaded', sa.Float(), nullable=False),
    sa.Column('driver_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_truck'))
    )
    op.create_table('unload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('initial_lat', sa.Float(), nullable=False),
    sa.Column('initial_lon', sa.Float(), nullable=False),
    sa.Column('initial_height', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unload_type', sa.Enum('HYDRAULIC', 'MECHANICAL', 'GRAVITY', name='unloadtype'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('angle', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('payload_type', sa.Enum('GRAVEL', 'SAND', 'CLAY', 'WET_ORE', name='payloadtype'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unload'))
    )
    op.create_table('trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trail_type', sa.Enum('COMMON', 'UNCOMMON', 'SPECIAL', name='trailtype'), nullable=False),
    sa.Column('raw_graph', sa.Text(), nullable=False),
    sa.Column('shovel_id', sa.Integer(), nullable=False),
    sa.Column('unload_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shovel_id'], ['shovel.id'], name=op.f('fk_trail_shovel_id_shovel'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unload_id'], ['unload.id'], name=op.f('fk_trail_unload_id_unload'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trail'))
    )
    op.create_table('trail_truck_association',
    sa.Column('trail_id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trail_id'], ['trail.id'], name=op.f('fk_trail_truck_association_trail_id_trail'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['truck_id'], ['truck.id'], name=op.f('fk_trail_truck_association_truck_id_truck'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trail_id', 'truck_id', name=op.f('pk_trail_truck_association'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trail_truck_association')
    op.drop_table('trail')
    op.drop_table('unload')
    op.drop_table('truck')
    op.drop_table('shovel')
    op.execute('DROP TYPE payloadtype;')
    op.execute('DROP TYPE trailtype;')
    op.execute('DROP TYPE unloadtype;')
    # ### end Alembic commands ###
