"""Add ShovelTemplate, TruckTemplate, UnloadTemplate

Revision ID: 660043dae00e
Revises: f07a8f73270d
Create Date: 2025-07-30 19:05:06.513183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '660043dae00e'
down_revision = 'f07a8f73270d'
branch_labels = None
depends_on = None


def upgrade():
    pt_enum = postgresql.ENUM('GRAVEL', 'SAND', 'CLAY', 'WET_ORE', name='payloadtype', create_type=False)
    ut_enum = postgresql.ENUM('HYDRAULIC', 'MECHANICAL', 'GRAVITY', name='unloadtype', create_type=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shovel_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bucket_volume', sa.Float(), nullable=False),
    sa.Column('bucket_lift_speed', sa.Float(), nullable=False),
    sa.Column('arm_turn_speed', sa.Float(), nullable=False),
    sa.Column('bucket_dig_speed', sa.Float(), nullable=False),
    sa.Column('bucket_fill_speed', sa.Float(), nullable=False),
    sa.Column('bucket_fill_coef', sa.Float(), nullable=False),
    sa.Column('arm_inertia_coef', sa.Float(), nullable=False),
    sa.Column('return_move_coef', sa.Float(), nullable=False),
    sa.Column('payload_type', pt_enum, nullable=False),
    sa.Column('init_cycles', sa.Integer(), nullable=False),
    sa.Column('wear_rate', sa.Float(), nullable=False),
    sa.Column('driver_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shovel_template'))
    )
    op.create_table('truck_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body_volume', sa.Float(), nullable=False),
    sa.Column('speed_empty', sa.Float(), nullable=False),
    sa.Column('speed_loaded', sa.Float(), nullable=False),
    sa.Column('driver_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_truck_template'))
    )
    op.create_table('unload_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unload_type', ut_enum, nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('angle', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('payload_type', pt_enum, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unload_template'))
    )
    with op.batch_alter_table('shovel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_shovel_template_id_shovel_template'), 'shovel_template', ['template_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_truck_template_id_truck_template'), 'truck_template', ['template_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('unload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_unload_template_id_unload_template'), 'unload_template', ['template_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unload', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_unload_template_id_unload_template'), type_='foreignkey')
        batch_op.drop_column('template_id')

    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_truck_template_id_truck_template'), type_='foreignkey')
        batch_op.drop_column('template_id')

    with op.batch_alter_table('shovel', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shovel_template_id_shovel_template'), type_='foreignkey')
        batch_op.drop_column('template_id')

    op.drop_table('unload_template')
    op.drop_table('truck_template')
    op.drop_table('shovel_template')
    # ### end Alembic commands ###
