"""New fields for Shovel, Truck and Unload

Revision ID: 689dff3c9f22
Revises: 660043dae00e
Create Date: 2025-08-05 13:10:34.737909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689dff3c9f22'
down_revision = '660043dae00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shovel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_operating_time', sa.Integer(), server_default='12', nullable=False))
        batch_op.add_column(sa.Column('initial_failure_count', sa.Integer(), server_default='100', nullable=False))
        batch_op.add_column(sa.Column('average_repair_duration', sa.Integer(), server_default='8', nullable=False))

    with op.batch_alter_table('shovel_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_operating_time', sa.Integer(), server_default='12', nullable=False))
        batch_op.add_column(sa.Column('initial_failure_count', sa.Integer(), server_default='100', nullable=False))
        batch_op.add_column(sa.Column('average_repair_duration', sa.Integer(), server_default='8', nullable=False))

    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_operating_time', sa.Integer(), server_default='12', nullable=False))
        batch_op.add_column(sa.Column('initial_failure_count', sa.Integer(), server_default='50', nullable=False))
        batch_op.add_column(sa.Column('average_repair_duration', sa.Integer(), server_default='4', nullable=False))

    with op.batch_alter_table('truck_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_operating_time', sa.Integer(), server_default='12', nullable=False))
        batch_op.add_column(sa.Column('initial_failure_count', sa.Integer(), server_default='50', nullable=False))
        batch_op.add_column(sa.Column('average_repair_duration', sa.Integer(), server_default='4', nullable=False))

    with op.batch_alter_table('unload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trucks_at_once', sa.Integer(), server_default='100', nullable=False))
        batch_op.add_column(sa.Column('initial_operating_time', sa.Integer(), server_default='24', nullable=False))
        batch_op.add_column(sa.Column('initial_failure_count', sa.Integer(), server_default='50', nullable=False))
        batch_op.add_column(sa.Column('average_repair_duration', sa.Integer(), server_default='24', nullable=False))

    with op.batch_alter_table('unload_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trucks_at_once', sa.Integer(), server_default='100', nullable=False))
        batch_op.add_column(sa.Column('initial_operating_time', sa.Integer(), server_default='24', nullable=False))
        batch_op.add_column(sa.Column('initial_failure_count', sa.Integer(), server_default='50', nullable=False))
        batch_op.add_column(sa.Column('average_repair_duration', sa.Integer(), server_default='24', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unload_template', schema=None) as batch_op:
        batch_op.drop_column('average_repair_duration')
        batch_op.drop_column('initial_failure_count')
        batch_op.drop_column('initial_operating_time')
        batch_op.drop_column('trucks_at_once')

    with op.batch_alter_table('unload', schema=None) as batch_op:
        batch_op.drop_column('average_repair_duration')
        batch_op.drop_column('initial_failure_count')
        batch_op.drop_column('initial_operating_time')
        batch_op.drop_column('trucks_at_once')

    with op.batch_alter_table('truck_template', schema=None) as batch_op:
        batch_op.drop_column('average_repair_duration')
        batch_op.drop_column('initial_failure_count')
        batch_op.drop_column('initial_operating_time')

    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_column('average_repair_duration')
        batch_op.drop_column('initial_failure_count')
        batch_op.drop_column('initial_operating_time')

    with op.batch_alter_table('shovel_template', schema=None) as batch_op:
        batch_op.drop_column('average_repair_duration')
        batch_op.drop_column('initial_failure_count')
        batch_op.drop_column('initial_operating_time')

    with op.batch_alter_table('shovel', schema=None) as batch_op:
        batch_op.drop_column('average_repair_duration')
        batch_op.drop_column('initial_failure_count')
        batch_op.drop_column('initial_operating_time')

    # ### end Alembic commands ###
