"""Add scenario relation to TrailTruckAssociation

Revision ID: 741a88f7abe1
Revises: 173b757501f6
Create Date: 2025-08-14 14:41:03.415736

"""
from alembic import op
from datetime import datetime
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741a88f7abe1'
down_revision = '173b757501f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail_truck_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_trail_truck_association_scenario_id_scenario'), 'scenario', ['scenario_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###

    conn = op.get_bind()

    # Находим первый карьер
    quarry_id = conn.scalar(
        sa.text("SELECT id FROM quarry ORDER BY id LIMIT 1")
    )

    if quarry_id:
        # Вычисляем временной диапазон (с 10 до 18 текущего дня)
        today = datetime.now()
        start_time = datetime(today.year, today.month, today.day, 10, 0)
        end_time = datetime(today.year, today.month, today.day, 18, 0)

        # Создаем сценарий по умолчанию и сразу получаем его ID
        scenario_id = conn.scalar(
            sa.text("""
                    INSERT INTO scenario (name, start_time, end_time, is_auto_truck_distribution, quarry_id, created_at,
                                          updated_at)
                    VALUES ('Сценарий 1', :start_time, :end_time, TRUE, :quarry_id, :now, :now) RETURNING id
                    """).bindparams(
                start_time=start_time,
                end_time=end_time,
                quarry_id=quarry_id,
                now=today
            )
        )

        if scenario_id:
            # Обновляем все существующие маршруты
            conn.execute(
                sa.text("UPDATE trail_truck_association SET scenario_id = :scenario_id").bindparams(scenario_id=scenario_id)
            )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail_truck_association', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trail_truck_association_scenario_id_scenario'), type_='foreignkey')
        batch_op.drop_column('scenario_id')

    # ### end Alembic commands ###
