"""Add primary_key to scenario_id in TrailTruckAssociation

Revision ID: 77aa09bc992e
Revises: 741a88f7abe1
Create Date: 2025-08-16 17:24:58.924760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77aa09bc992e'
down_revision = '741a88f7abe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail_truck_association', schema=None) as batch_op:
        # Удаляем старый первичный ключ
        batch_op.drop_constraint('pk_trail_truck_association', type_='primary')

        # Делаем scenario_id обязательным
        batch_op.alter_column('scenario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

        # Создаем новый составной первичный ключ
        batch_op.create_primary_key('pk_trail_truck_association',
                                   ['scenario_id', 'trail_id', 'truck_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail_truck_association', schema=None) as batch_op:
        # Удаляем новый первичный ключ
        batch_op.drop_constraint('pk_trail_truck_association', type_='primary')

        # Возвращаем старый первичный ключ
        batch_op.create_primary_key('pk_trail_truck_association',
                                   ['trail_id', 'truck_id'])

        # Возвращаем scenario_id к nullable
        batch_op.alter_column('scenario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###