"""Add shift change fields to Quarry

Revision ID: 8d394792dc14
Revises: c5fb8550f985
Create Date: 2025-09-23 14:15:16.421039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d394792dc14'
down_revision = 'c5fb8550f985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_change_offset', sa.Integer(), server_default='690', nullable=False))
        batch_op.add_column(sa.Column('shift_change_duration', sa.Integer(), server_default='30', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quarry', schema=None) as batch_op:
        batch_op.drop_column('shift_change_duration')
        batch_op.drop_column('shift_change_offset')

    # ### end Alembic commands ###
