"""New reliability related fields for Scenario

Revision ID: 9daa452a370b
Revises: 2f3ca3217c27
Create Date: 2025-10-03 11:51:42.883002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9daa452a370b'
down_revision = '2f3ca3217c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_calc_reliability_enabled', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('process_num', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('init_runs_num', sa.Integer(), server_default='15', nullable=False))
        batch_op.add_column(sa.Column('step_runs_num', sa.Integer(), server_default='15', nullable=False))
        batch_op.add_column(sa.Column('max_runs_num', sa.Integer(), server_default='105', nullable=False))
        batch_op.add_column(sa.Column('alpha', sa.Float(), server_default='0.05', nullable=False))
        batch_op.add_column(sa.Column('r_target', sa.Float(), server_default='0.05', nullable=False))
        batch_op.add_column(sa.Column('delta_target', sa.Float(), server_default='0.01', nullable=False))
        batch_op.add_column(sa.Column('consecutive', sa.Integer(), server_default='2', nullable=False))
        batch_op.add_column(sa.Column('boot_b', sa.Integer(), server_default='5000', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.drop_column('boot_b')
        batch_op.drop_column('consecutive')
        batch_op.drop_column('delta_target')
        batch_op.drop_column('r_target')
        batch_op.drop_column('alpha')
        batch_op.drop_column('max_runs_num')
        batch_op.drop_column('step_runs_num')
        batch_op.drop_column('init_runs_num')
        batch_op.drop_column('process_num')
        batch_op.drop_column('is_calc_reliability_enabled')

    # ### end Alembic commands ###
