"""Add ShiftChangeArea and FuelStation models

Revision ID: a06b87cc0807
Revises: b7dcacd91b4a
Create Date: 2025-08-11 14:30:42.850116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06b87cc0807'
down_revision = 'b7dcacd91b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_station_template',
    sa.Column('num_pumps', sa.Integer(), server_default='2', nullable=False),
    sa.Column('flow_rate', sa.Float(), server_default='2.0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fuel_station_template'))
    )
    op.create_table('fuel_station',
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('quarry_id', sa.Integer(), nullable=False),
    sa.Column('num_pumps', sa.Integer(), server_default='2', nullable=False),
    sa.Column('flow_rate', sa.Float(), server_default='2.0', nullable=False),
    sa.Column('initial_lat', sa.Float(), nullable=False),
    sa.Column('initial_lon', sa.Float(), nullable=False),
    sa.Column('initial_height', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quarry_id'], ['quarry.id'], name=op.f('fk_fuel_station_quarry_id_quarry'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['fuel_station_template.id'], name=op.f('fk_fuel_station_template_id_fuel_station_template'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fuel_station'))
    )
    op.create_table('shift_change_area',
    sa.Column('quarry_id', sa.Integer(), nullable=False),
    sa.Column('initial_lat', sa.Float(), nullable=False),
    sa.Column('initial_lon', sa.Float(), nullable=False),
    sa.Column('initial_height', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quarry_id'], ['quarry.id'], name=op.f('fk_shift_change_area_quarry_id_quarry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_change_area'))
    )
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_capacity', sa.Float(), server_default='200', nullable=False))
        batch_op.add_column(sa.Column('fuel_threshold_critical', sa.Float(), server_default='50', nullable=False))
        batch_op.add_column(sa.Column('fuel_threshold_planned', sa.Float(), server_default='80', nullable=False))
        batch_op.add_column(sa.Column('fuel_level', sa.Float(), server_default='200', nullable=False))
        batch_op.add_column(sa.Column('fuel_idle_lph', sa.Float(), server_default='15', nullable=False))
        batch_op.add_column(sa.Column('fuel_specific_consumption', sa.Float(), server_default='205', nullable=False))
        batch_op.add_column(sa.Column('fuel_density', sa.Float(), server_default='0.82', nullable=False))
        batch_op.add_column(sa.Column('engine_power_kw', sa.Float(), server_default='1716', nullable=False))

    with op.batch_alter_table('truck_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_capacity', sa.Float(), server_default='200', nullable=False))
        batch_op.add_column(sa.Column('fuel_threshold_critical', sa.Float(), server_default='50', nullable=False))
        batch_op.add_column(sa.Column('fuel_threshold_planned', sa.Float(), server_default='80', nullable=False))
        batch_op.add_column(sa.Column('fuel_level', sa.Float(), server_default='200', nullable=False))
        batch_op.add_column(sa.Column('fuel_idle_lph', sa.Float(), server_default='15', nullable=False))
        batch_op.add_column(sa.Column('fuel_specific_consumption', sa.Float(), server_default='205', nullable=False))
        batch_op.add_column(sa.Column('fuel_density', sa.Float(), server_default='0.82', nullable=False))
        batch_op.add_column(sa.Column('engine_power_kw', sa.Float(), server_default='1716', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('truck_template', schema=None) as batch_op:
        batch_op.drop_column('engine_power_kw')
        batch_op.drop_column('fuel_density')
        batch_op.drop_column('fuel_specific_consumption')
        batch_op.drop_column('fuel_idle_lph')
        batch_op.drop_column('fuel_level')
        batch_op.drop_column('fuel_threshold_planned')
        batch_op.drop_column('fuel_threshold_critical')
        batch_op.drop_column('fuel_capacity')

    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_column('engine_power_kw')
        batch_op.drop_column('fuel_density')
        batch_op.drop_column('fuel_specific_consumption')
        batch_op.drop_column('fuel_idle_lph')
        batch_op.drop_column('fuel_level')
        batch_op.drop_column('fuel_threshold_planned')
        batch_op.drop_column('fuel_threshold_critical')
        batch_op.drop_column('fuel_capacity')

    op.drop_table('shift_change_area')
    op.drop_table('fuel_station')
    op.drop_table('fuel_station_template')
    # ### end Alembic commands ###
