"""Add UploadedFile and MapOverlay

Revision ID: a43abb6acab2
Revises: 8520318762c4
Create Date: 2025-09-12 17:10:16.547703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a43abb6acab2'
down_revision = '8520318762c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=4096), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_file')),
    sa.UniqueConstraint('name', name=op.f('uq_uploaded_file_name'))
    )
    op.create_table('map_overlay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('quarry_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=9), server_default='#212121FF', nullable=False),
    sa.Column('anchor_lat', sa.Float(), nullable=True),
    sa.Column('anchor_lon', sa.Float(), nullable=True),
    sa.Column('anchor_height', sa.Float(), nullable=True),
    sa.Column('geojson_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('geojson_data IS NOT NULL OR source_file_id IS NOT NULL', name=op.f('ck_map_overlay_source_file_or_geojson_data_is_not_null')),
    sa.CheckConstraint("color ~ '^#[A-F0-9]{8}$'", name=op.f('ck_map_overlay_color_is_rgba_hex')),
    sa.ForeignKeyConstraint(['quarry_id'], ['quarry.id'], name=op.f('fk_map_overlay_quarry_id_quarry'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['uploaded_file.id'], name=op.f('fk_map_overlay_source_file_id_uploaded_file'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map_overlay')),
    sa.UniqueConstraint('source_file_id', name=op.f('uq_map_overlay_source_file_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_overlay')
    op.drop_table('uploaded_file')
    # ### end Alembic commands ###
