"""Add Quarry

Revision ID: b7dcacd91b4a
Revises: 34d2db5b9f3c
Create Date: 2025-08-06 07:09:55.809662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7dcacd91b4a'
down_revision = '34d2db5b9f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Add Quarry table
    op.create_table('quarry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('center_lat', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('center_lon', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('center_height', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('timezone', sa.String(length=100), server_default='Europe/Moscow', nullable=False),
    sa.Column('shift_config', sa.JSON(), server_default='[{"begin_offset": 480, "end_offset": 1200}, {"begin_offset": 1200, "end_offset": 1920}]', nullable=False),
    sa.Column('work_break_duration', sa.Integer(), server_default='10', nullable=False),
    sa.Column('work_break_rate', sa.Integer(), server_default='1', nullable=False),
    sa.Column('lunch_break_offset', sa.Integer(), server_default='360', nullable=False),
    sa.Column('lunch_break_duration', sa.Integer(), server_default='60', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quarry'))
    )

    # 2.1. Add nullable quarry_id field to Shovel
    with op.batch_alter_table('shovel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quarry_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_shovel_quarry_id_quarry'), 'quarry', ['quarry_id'], ['id'], ondelete='CASCADE')

    # 2.2. Add nullable quarry_id field to Truck
    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quarry_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_truck_quarry_id_quarry'), 'quarry', ['quarry_id'], ['id'], ondelete='CASCADE')

    # 2.3. Add nullable quarry_id field to Unload
    with op.batch_alter_table('unload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quarry_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_unload_quarry_id_quarry'), 'quarry', ['quarry_id'], ['id'], ondelete='CASCADE')

    # 3. Create default quarry record
    quarry = sa.sql.table('quarry', sa.sql.column('name', sa.String))
    stmt = quarry.insert().values(name='Карьер 1')
    op.execute(stmt)
    # It should definitely be 1, isn't it?
    quarry_id = 1

    # 4.1. Set quarry_id = 1 for all Shovel records
    shovel = sa.sql.table('shovel', sa.sql.column('quarry_id', sa.Integer))
    stmt = shovel.update().values(quarry_id=quarry_id)
    op.execute(stmt)

    # 4.2. Set quarry_id = 1 for all Truck records
    truck = sa.sql.table('truck', sa.sql.column('quarry_id', sa.Integer))
    stmt = truck.update().values(quarry_id=quarry_id)
    op.execute(stmt)

    # 4.3. Set quarry_id = 1 for all Unload records
    unload = sa.sql.table('unload', sa.sql.column('quarry_id', sa.Integer))
    stmt = unload.update().values(quarry_id=quarry_id)
    op.execute(stmt)

    # 5.1. Make quarry_id field non-nullable for Shovel
    op.alter_column('shovel', 'quarry_id', nullable=False)
    # 5.2. Make quarry_id field non-nullable for Truck
    op.alter_column('truck', 'quarry_id', nullable=False)
    # 5.3. Make quarry_id field non-nullable for Unload
    op.alter_column('unload', 'quarry_id', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unload', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_unload_quarry_id_quarry'), type_='foreignkey')
        batch_op.drop_column('quarry_id')

    with op.batch_alter_table('truck', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_truck_quarry_id_quarry'), type_='foreignkey')
        batch_op.drop_column('quarry_id')

    with op.batch_alter_table('shovel', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_shovel_quarry_id_quarry'), type_='foreignkey')
        batch_op.drop_column('quarry_id')

    op.drop_table('quarry')
    # ### end Alembic commands ###
