"""Add PlannedIdle

Revision ID: c5fb8550f985
Revises: a43abb6acab2
Create Date: 2025-09-22 10:45:17.911167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fb8550f985'
down_revision = 'a43abb6acab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planned_idle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quarry_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("vehicle_type IN ('truck', 'shovel')", name=op.f('ck_planned_idle_vehicle_type_is_valid')),
    sa.ForeignKeyConstraint(['quarry_id'], ['quarry.id'], name=op.f('fk_planned_idle_quarry_id_quarry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planned_idle'))
    )
    with op.batch_alter_table('planned_idle', schema=None) as batch_op:
        batch_op.create_index('time_range', ['start_time', 'end_time'], unique=False)
        batch_op.create_index('vehicle_type_id', ['vehicle_type', 'vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planned_idle', schema=None) as batch_op:
        batch_op.drop_index('vehicle_type_id')
        batch_op.drop_index('time_range')

    op.drop_table('planned_idle')
    # ### end Alembic commands ###
