"""add RoadNet

Revision ID: fea74ce0faa7
Revises: 049327069ed2
Create Date: 2025-08-14 16:28:10.744884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fea74ce0faa7'
down_revision = '049327069ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_net',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quarry_id', sa.Integer(), nullable=False),
    sa.Column('geojson_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['quarry_id'], ['quarry.id'], name=op.f('fk_road_net_quarry_id_quarry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_road_net'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('road_net')
    # ### end Alembic commands ###
